### ISSUE TITLE
Issue with the RIR dataflow

### ISSUE THREAD

**Issue by sosna** [ecbsdmx/t2swdc#46]
Using the country groupings with (at least) the RIR dataflow causes a strange behavior:
- On the 1st screen of the wizard, click on `Monetary and financial statistics`
- On the 2nd screen of the wizard, click on `Retail Interest Rates`
- On the 3rd screen of the wizard, select `All MU countries` for the reference area
- Then click on the small `x` on the right of the select field. Instead of only deselecting the countries, it adds values for Frequency, IR business coverage and Interest rate type.

This does not happen with other dataflows such ICP, BSI, BKN, GFS, etc. It could be related to the fact that there are less country data for RIR (only 19 reference areas vs. more than 30 for all the other flows).

**Comment by Tzaphkiel** [comment]
**Cannot fix issue.**

Select2 does not come with an event for `removeall` action. 

Instead it triggers a progressive removal of items. 
During this progression, the other dimensions are filtered. When the list of codes for a dimension becomes a single code, that code is added to the dimension as a filter.
The dimension filters thus modified then stay active.
