### ISSUE TITLE
Live connection between the connector and the Web Services

### ISSUE THREAD

**Issue by Tzaphkiel** [ecbsdmx/t2swdc#57]
It would be nice to have the possibility to maintain a **live connection** with the t2swdc and the SDW web services. 

How this is implemented or if it is possible still has to be discussed. 
I enter the issue here for tracking and not to forget about it.

![image](https://cloud.githubusercontent.com/assets/644489/18467968/305ecb06-79a2-11e6-8fc7-b403578fb033.png)

**Comment by airosa** [comment]
Unfortunately Live Connect is not supported by Tableau for Web Data Connector. That means that you always must use Extract with any Web Data Connector.
