### ISSUE TITLE
Update tableau script tag

### ISSUE THREAD

**Issue by airosa** [ecbsdmx/t2swdc#68]
From http://stackoverflow.com/questions/36078712/web-data-connector-tableau:

- Update your script tag that points to https://online.tableau.com/javascripts/api/tableauwdc-1.1.0.js and instead point it to https://connectors.tableau.com/libs/tableauwdc-1.1.0.js.

Both of those versions of the file are old and the one on online.tableau.com actually has a bug in it (that has been fixed). We messed up early in the lifetime of the web data connector and weren't properly following semver. Now we are. All future versions of the library will follow semver and be hosted on connectors.tableau.com/libs.

**Comment by nikornnanta** [comment]
t on issue

**Comment by airosa** [comment]
This will be fixed by #71
